language: python
sudo: required
services:
  - docker
cache: pip
os:
  - linux
python:
  - "3.6"
script:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region us-east-1)
  - pip install -r requirements/test.txt
  - pipenv install --dev
  - ./lintstats.sh
  - ./tests/docker_tests.sh
  - pipenv run nose2
after_success:
  - coveralls
