language: python
sudo: required
cache: pip
os:
  - linux
python:
  - "3.6"
services:
  - docker
script:
  - docker build ./ -t arxiv/zero
  - pip install -r requirements/test.txt
  - nose2 --with-coverage
after_success:
  - coveralls
