language: python
sudo: required
services:
  - docker
cache: pip
os:
  - linux
python:
  - "3.6"
script:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run ./lintstats.sh
  - ./tests/docker_tests.sh
  - pipenv run nose2
after_success:
  - coveralls
