version: '3'

services:
  zero-test-redis:
    image: redis
    container_name: zero-test-redis
    networks:
      - zero-test
  zero-worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    environment:
      REDIS_ENDPOINT: "zero-test-redis:6379"
    networks:
      - zero-test
    depends_on:
      - zero-test-redis
  zero-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zero-api
    environment:
      REDIS_ENDPOINT: "zero-test-redis:6379"
    ports:
      - "8003:8000"
    networks:
      - zero-test
    depends_on:
      - zero-test-redis
      - zero-worker

networks:
  zero-test:
